### ISSUE TITLE
liver MR dataset

### ISSUE THREAD

**Issue by JunMa11** [bbbbbbzhou/APA2Seg-Net#1]
Dear Bo Zhou @bbbbbbzhou ,

Thanks for sharing this great work.

I'm looking for publicly available large-scale liver MR 3D data.

Do you have any suggestions beyond CHAOS (only 20 cases)?

Best,
Jun

**Comment by bbbbbbzhou** [comment]
Hi Jun, thank you for your interest in our work. 
I am not sure about the publically available large-scale MR dataset. But the public dataset we used in our paper were from LiTS (131 cases) and CHAOS (20 cases), and they are all CT data. 
Bo

**Comment by JunMa11** [comment]
Got it. Thanks for your reply very much.
